spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/breadcast   # DB ??
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  # ???? ?? ????? ?? (?? ????? ?? ? ???)
    properties:
      hibernate:
        format_spl: true

logging:
  level:    # ?? ?? ???
    org.hibernate.SQL: debug    # Hibernate? ???? ?? SQL ?? ??(SQL? ??)? ??? ??. ???? ?? ?? ??
    org.hibernate.type: trace   # Hibernate? SQL ?? ? ????? ???? ?? ??
